apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop-app
  labels:
    app: petshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petshop
  template:
    metadata:
      labels:
        app: petshop
    spec:
      containers:
        - name: tomcat-jpetstore
          image: sholly333/tomcat-jpetstore:jenkins-Petshop-App-12
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petshop-service
spec:
  selector:
    app: petshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
